# Generated by Django 4.1.6 on 2024-02-23 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
                ('tier', models.IntegerField()),
                ('isReal', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
                ('first_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first_input', to='items.item')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_output', to='items.item')),
                ('second_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second_input', to='items.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='simplestWayToMake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_simplest_to_make', to='items.transformation'),
        ),
        migrations.AddConstraint(
            model_name='transformation',
            constraint=models.UniqueConstraint(fields=('first_input', 'second_input'), name='unique_transformation_inputs'),
        ),
    ]
