# Generated by Django 4.1.6 on 2024-03-13 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='simplestWayToMake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_simplest_to_make', to='items.transformation'),
        ),
        migrations.CreateModel(
            name='ItemPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_first_in_pair', to='items.item')),
                ('second_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_second_in_pair', to='items.item')),
                ('transformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformation', to='items.transformation')),
            ],
        ),
    ]
