# Generated by Django 4.1.6 on 2024-03-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_simplestwaytomake_itempair'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='emoji',
            field=models.TextField(null=True),
        ),
    ]
