# Generated by Django 4.1.6 on 2024-03-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itempair_from_ab_c_transformation_input_pair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempair',
            name='transformation',
        ),
    ]
