# Generated by Django 4.1.6 on 2024-03-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_itempair_transformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='first_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_first_input', to='items.item'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='input_pair',
            field=models.ForeignKey(default='100000', on_delete=django.db.models.deletion.CASCADE, related_name='as_inputs', to='items.itempair'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transformation',
            name='second_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_second_input', to='items.item'),
        ),
    ]
