# Generated by Django 5.1.7 on 2025-09-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_transformation_first_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='canCombine',
            field=models.BooleanField(default=True),
        ),
    ]
