# Generated by Django 5.1.7 on 2025-11-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_cancombine'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='transformation',
            name='unique_transformation_inputs',
        ),
        migrations.AddConstraint(
            model_name='transformation',
            constraint=models.UniqueConstraint(fields=('input_pair',), name='unique_transformation_inputs'),
        ),
        migrations.AddField(
            model_name='outcomefrequency',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_outcome_input', to='items.item'),
        ),
        migrations.AddField(
            model_name='outcomefrequency',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_outcome_result', to='items.item'),
        ),
        migrations.AddConstraint(
            model_name='outcomefrequency',
            constraint=models.UniqueConstraint(fields=('item', 'outcome'), name='unique_outcome_frequency'),
        ),
    ]
