# Generated by Django 5.1.7 on 2025-11-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_outcomefrequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcomefrequency',
            old_name='timeCreated',
            new_name='timecreated',
        ),
        migrations.RenameField(
            model_name='outcomefrequency',
            old_name='timeUpdated',
            new_name='timeupdated',
        ),
    ]
